version: '3.6'
services:
  consul:
    image: consul:latest
    restart: always
    container_name: dll-consul-master
    volumes:
    - ./consul:/tmp/consul
    ports:
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8302:8302
    - 8302:8302/udp
    - 8400:8400
    - 8500:8500
    - 53:53/udp
    command: consul agent -data-dir=/tmp/consul -dev -client=0.0.0.0